site_name: jsonrpcserver
site_url: https://explodinglabs.com/jsonrpcserver/
repo_url: https://github.com/explodinglabs/jsonrpcserver
theme:
  name: material
  features:
    - navigation.footer
    - palette.toggle
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Installation: installation.md
  - Methods: methods.md
  - Dispatch: dispatch.md
  - Async: async.md
  - FAQ: faq.md
  - Examples: examples.md
